name: pets_next_door_flutter
description: Pets Next Door
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  change_app_package_name: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.4
  kakao_flutter_sdk_auth: ^1.5.0
  go_router: ^10.0.0
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  dio: ^5.2.1+1


dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  # a tool for running code generators
  build_runner: ^2.4.6
  # the code generator
  riverpod_generator: ^2.2.3
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^1.3.2
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.4.0

  flutter_flavorizr: ^2.2.1

  flutter_lints: ^2.0.0

flutter:
  assets:
  - assets/imgs/
  - assets/svgs/
  uses-material-design: true
  generate: true

