name: pets_next_door_flutter
description: Pets Next Door
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.4
  kakao_flutter_sdk_auth: ^1.5.0
  kakao_flutter_sdk_user: ^1.4.1
  go_router: ^10.0.0
  intl: ^0.18.1
  dio: ^5.2.1+1
  freezed_annotation: ^2.4.1
  google_maps_flutter: ^2.4.0
  retrofit: ^4.0.3
  infinite_scroll_pagination: ^4.0.0

  # UI
  cupertino_will_pop_scope: ^1.2.1 #pop scope (스와이프 백 제스쳐 지원)
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  flutter_easyloading: ^3.0.5

  # 상태관리
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  # a tool for running code generators
  build_runner: ^2.4.6
  # the code generator
  riverpod_generator: ^2.2.3
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^1.3.2
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.4.0

  flutter_flavorizr: ^2.2.1

  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/imgs/
    - assets/fonts/
    - assets/imgs/pet/
    - assets/svgs/
    - assets/svgs/login/
    - assets/svgs/home/
    - assets/svgs/pet/
    

  uses-material-design: true
  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
