name: pets_next_door_flutter
description: Pets Next Door
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.4
  kakao_flutter_sdk_auth: ^1.5.0
  kakao_flutter_sdk_user: ^1.4.1

  # UI
  cupertino_will_pop_scope: ^1.2.1 #pop scope (스와이프 백 제스쳐 지원)
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  flutter_easyloading: ^3.0.5
  cupertino_icons: ^1.0.2

  # 상태관리
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

  # 네트워크
  retrofit: ^4.0.3
  dio: ^5.2.1+1

  # DI
  get_it: ^7.2.0

  # 라우팅
  go_router: ^13.0.1

  # Utils
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  flutter_dotenv: ^5.1.0 # 환경변수 설정
  shared_preferences: ^2.2.2 # 로컬 캐싱

  # 앱 정보
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.2 # 네트워크 API Generator

flutter:
  assets:
    - .env
    - assets/fonts/
    - assets/imgs/
    - assets/imgs/pet/
    - assets/imgs/launch/
    - assets/svgs/
    - assets/svgs/login/
    - assets/svgs/home/
    - assets/svgs/pet/

  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
