// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWQrnTiWCZKGemXCkALEQC89KsO84m1Zk',
    appId: '1:424678055013:web:7e8c5512cb8cd0a7647a8c',
    messagingSenderId: '424678055013',
    projectId: 'petsnextdoor-prod-1a02e',
    authDomain: 'petsnextdoor-prod-1a02e.firebaseapp.com',
    storageBucket: 'petsnextdoor-prod-1a02e.appspot.com',
    measurementId: 'G-CSZQQNM57H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHNSTUZhblGy9DLfHQ723iOaMHacVIVR8',
    appId: '1:424678055013:android:3285f962ae911d3f647a8c',
    messagingSenderId: '424678055013',
    projectId: 'petsnextdoor-prod-1a02e',
    storageBucket: 'petsnextdoor-prod-1a02e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVckw9EYmZDS0hLEzv56zi7XuCeSG3GRE',
    appId: '1:424678055013:ios:68a3249e63edf50d647a8c',
    messagingSenderId: '424678055013',
    projectId: 'petsnextdoor-prod-1a02e',
    storageBucket: 'petsnextdoor-prod-1a02e.appspot.com',
    iosClientId: '424678055013-lqikhot4d87ifooit42092ukp8uo1e4g.apps.googleusercontent.com',
    iosBundleId: 'co.yellowtoast.pets-next-door-flutter',
  );
}
