// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB79s6OOMUyomJmeGev11N7XPaMHAPPvn4',
    appId: '1:231574029969:web:949af1cd9cc4a142406130',
    messagingSenderId: '231574029969',
    projectId: 'petsnextdoor-788a0',
    authDomain: 'petsnextdoor-788a0.firebaseapp.com',
    storageBucket: 'petsnextdoor-788a0.appspot.com',
    measurementId: 'G-C7Q3XKJZMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8oaNG89iH-F6snzOmAwJyKWIuUG0ZOJQ',
    appId: '1:231574029969:android:5fd849ba305e4ad5406130',
    messagingSenderId: '231574029969',
    projectId: 'petsnextdoor-788a0',
    storageBucket: 'petsnextdoor-788a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrvg5hkQ9uz1Zk_zbUZKHMgLDohT8n1p0',
    appId: '1:231574029969:ios:d2d957b73209d7fa406130',
    messagingSenderId: '231574029969',
    projectId: 'petsnextdoor-788a0',
    storageBucket: 'petsnextdoor-788a0.appspot.com',
    iosClientId:
        '231574029969-6g4o5a6ec3o3n073i57b225m1ibh6107.apps.googleusercontent.com',
    iosBundleId: 'co.yellowtoast.pets-next-door-flutter.dev',
  );
}
