// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZykZOj7VD-tWfwQy02mEMtN6gv9sYCo0',
    appId: '1:374077406173:web:6c398b93d4644b94e2d434',
    messagingSenderId: '374077406173',
    projectId: 'petsnextdoor-prod',
    authDomain: 'petsnextdoor-prod.firebaseapp.com',
    storageBucket: 'petsnextdoor-prod.appspot.com',
    measurementId: 'G-EDLWSREXVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfoGNPGEa-TXBzs9uA3BvwGViv5r6ChRA',
    appId: '1:374077406173:android:559973593ec98fc5e2d434',
    messagingSenderId: '374077406173',
    projectId: 'petsnextdoor-prod',
    storageBucket: 'petsnextdoor-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDevBxk0RukHBFjWO3YYJ_o2hxvjxIaVKQ',
    appId: '1:374077406173:ios:18a102d793f26831e2d434',
    messagingSenderId: '374077406173',
    projectId: 'petsnextdoor-prod',
    storageBucket: 'petsnextdoor-prod.appspot.com',
    iosClientId: '374077406173-f4995d6pokvn8l8vumft92iqt66m7in7.apps.googleusercontent.com',
    iosBundleId: 'co.yellowtoast.pets-next-door-flutter.prod',
  );
}
